// Hala Commercial Engine — PDF Compiler
// Generates professional Hala-branded PDF documents
// Uses browser-native PDF generation via print-to-PDF approach
// Documents: Proposals, Quotes, P&L Summaries, SLAs, ECR Scorecards

import type { Customer, Workspace, Quote, Proposal, PnLModel } from "./store";
import { formatSAR, formatPercent, getStageLabel, getApprovalRequirements, getRoleLabel, calculateECR } from "./store";

// ============================================================
// PDF TEMPLATE ENGINE
// ============================================================

const HALA_NAVY = "#1a2744";
const HALA_ACCENT = "#2a4a7f";
const HALA_LIGHT = "#f8f9fb";
const HALA_BORDER = "#e2e5ea";

function generateHeader(title: string, subtitle: string, docRef: string): string {
  return `
    <div style="display:flex;align-items:center;justify-content:space-between;padding:24px 32px;background:${HALA_NAVY};color:white;margin-bottom:0;">
      <div>
        <div style="font-size:10px;letter-spacing:2px;text-transform:uppercase;opacity:0.7;margin-bottom:4px;">HALA SUPPLY CHAIN SERVICES</div>
        <div style="font-size:22px;font-weight:700;font-family:'Source Serif 4',Georgia,serif;">${title}</div>
        <div style="font-size:12px;opacity:0.8;margin-top:4px;">${subtitle}</div>
      </div>
      <div style="text-align:right;">
        <div style="font-size:28px;font-weight:700;font-family:'Source Serif 4',Georgia,serif;letter-spacing:-1px;">H</div>
        <div style="font-size:9px;opacity:0.6;margin-top:2px;">${docRef}</div>
        <div style="font-size:9px;opacity:0.6;">${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</div>
      </div>
    </div>
  `;
}

function generateFooter(pageLabel: string): string {
  return `
    <div style="display:flex;align-items:center;justify-content:space-between;padding:12px 32px;border-top:1px solid ${HALA_BORDER};font-size:9px;color:#888;margin-top:auto;">
      <span>CONFIDENTIAL — Hala Supply Chain Services</span>
      <span>${pageLabel}</span>
      <span>Generated by Hala Commercial Engine</span>
    </div>
  `;
}

function generateSection(title: string, content: string): string {
  return `
    <div style="margin-bottom:24px;">
      <div style="font-size:14px;font-weight:700;font-family:'Source Serif 4',Georgia,serif;color:${HALA_NAVY};padding-bottom:8px;border-bottom:2px solid ${HALA_NAVY};margin-bottom:12px;">${title}</div>
      ${content}
    </div>
  `;
}

function generateTable(headers: string[], rows: string[][]): string {
  return `
    <table style="width:100%;border-collapse:collapse;font-size:11px;margin-bottom:16px;">
      <thead>
        <tr style="background:${HALA_LIGHT};">
          ${headers.map(h => `<th style="text-align:left;padding:8px 12px;border-bottom:2px solid ${HALA_BORDER};font-size:10px;text-transform:uppercase;letter-spacing:0.5px;color:#666;">${h}</th>`).join("")}
        </tr>
      </thead>
      <tbody>
        ${rows.map((row, i) => `
          <tr style="background:${i % 2 === 0 ? "white" : HALA_LIGHT};">
            ${row.map(cell => `<td style="padding:8px 12px;border-bottom:1px solid ${HALA_BORDER};">${cell}</td>`).join("")}
          </tr>
        `).join("")}
      </tbody>
    </table>
  `;
}

function generateKVGrid(items: { label: string; value: string }[], cols: number = 3): string {
  return `
    <div style="display:grid;grid-template-columns:repeat(${cols},1fr);gap:12px;margin-bottom:16px;">
      ${items.map(item => `
        <div style="padding:12px;background:${HALA_LIGHT};border-radius:6px;border:1px solid ${HALA_BORDER};">
          <div style="font-size:9px;text-transform:uppercase;letter-spacing:0.5px;color:#888;margin-bottom:4px;">${item.label}</div>
          <div style="font-size:14px;font-weight:600;color:${HALA_NAVY};font-family:'IBM Plex Mono',monospace;">${item.value}</div>
        </div>
      `).join("")}
    </div>
  `;
}

// ============================================================
// DOCUMENT GENERATORS
// ============================================================

export function generateQuotePDF(quote: Quote, workspace: Workspace, customer: Customer): string {
  const approvalReqs = getApprovalRequirements(quote.gpPercent, quote.palletVolume);

  return wrapDocument(`
    ${generateHeader("Commercial Quote", `${customer.name} — ${workspace.title}`, `QT-${quote.id.toUpperCase()}-V${quote.version}`)}
    <div style="padding:32px;">
      ${generateSection("Quote Summary", generateKVGrid([
        { label: "Customer", value: customer.name },
        { label: "Workspace", value: workspace.title },
        { label: "Region", value: customer.region },
        { label: "Quote Version", value: `v${quote.version}` },
        { label: "Status", value: quote.state.toUpperCase() },
        { label: "Date", value: quote.createdAt },
      ]))}

      ${generateSection("Pricing Schedule", generateTable(
        ["Service", "Rate", "Volume", "Monthly Revenue"],
        [
          ["Storage (per pallet/day)", `SAR ${quote.storageRate}`, `${quote.palletVolume.toLocaleString()} pallets`, formatSAR(quote.storageRate * quote.palletVolume * 30)],
          ["Inbound Handling", `SAR ${quote.inboundRate}/pallet`, `${quote.palletVolume.toLocaleString()}`, formatSAR(quote.inboundRate * quote.palletVolume)],
          ["Outbound Handling", `SAR ${quote.outboundRate}/pallet`, `${quote.palletVolume.toLocaleString()}`, formatSAR(quote.outboundRate * quote.palletVolume)],
        ]
      ))}

      ${generateSection("Financial Summary", generateKVGrid([
        { label: "Monthly Revenue", value: formatSAR(quote.monthlyRevenue) },
        { label: "Annual Revenue", value: formatSAR(quote.annualRevenue) },
        { label: "Total Cost", value: formatSAR(quote.totalCost) },
        { label: "Gross Profit", value: formatSAR(quote.gpAmount) },
        { label: "GP%", value: formatPercent(quote.gpPercent) },
        { label: "Pallet Volume", value: quote.palletVolume.toLocaleString() },
      ]))}

      ${generateSection("Approval Requirements", `
        <div style="font-size:11px;color:#555;margin-bottom:12px;">Based on GP% of ${formatPercent(quote.gpPercent)} and volume of ${quote.palletVolume.toLocaleString()} pallets:</div>
        ${generateTable(
          ["Role", "Type", "Status"],
          approvalReqs.map(r => [getRoleLabel(r.role), r.type === "feasibility" ? "Feasibility Confirmation" : "Full Approval", "Required"])
        )}
      `)}

      ${generateSection("Terms & Conditions", `
        <div style="font-size:11px;color:#555;line-height:1.6;">
          <p>1. All rates are quoted in Saudi Riyals (SAR) and are exclusive of VAT (15%).</p>
          <p>2. Storage rates are calculated on a per-pallet-per-day basis.</p>
          <p>3. This quote is valid for 30 days from the date of issue.</p>
          <p>4. Payment terms: Net 30 days from invoice date.</p>
          <p>5. Minimum contract period: 12 months.</p>
          <p>6. Volume commitments are subject to facility capacity confirmation.</p>
        </div>
      `)}
    </div>
    ${generateFooter("Quote Document")}
  `);
}

export function generateProposalPDF(proposal: Proposal, workspace: Workspace, customer: Customer): string {
  return wrapDocument(`
    ${generateHeader("Commercial Proposal", `${customer.name} — ${proposal.title}`, `PR-${proposal.id.toUpperCase()}-V${proposal.version}`)}
    <div style="padding:32px;">
      ${generateSection("Proposal Overview", generateKVGrid([
        { label: "Client", value: customer.name },
        { label: "Industry", value: customer.industry },
        { label: "Region", value: `${customer.city}, ${customer.region}` },
        { label: "Proposal Version", value: `v${proposal.version}` },
        { label: "Status", value: proposal.state.replace(/_/g, " ").toUpperCase() },
        { label: "Date", value: proposal.createdAt },
      ]))}

      ${generateSection("Document Sections", `
        <div style="font-size:11px;color:#555;">
          ${proposal.sections.map((s, i) => `
            <div style="display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid ${HALA_BORDER};">
              <div style="width:28px;height:28px;border-radius:50%;background:${HALA_NAVY};color:white;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:600;flex-shrink:0;">${i + 1}</div>
              <span style="font-weight:500;">${s}</span>
            </div>
          `).join("")}
        </div>
      `)}

      ${generateSection("Executive Summary", `
        <div style="font-size:11px;color:#555;line-height:1.7;">
          <p>Hala Supply Chain Services is pleased to present this proposal for ${customer.name}, addressing the requirements outlined in ${workspace.title}.</p>
          <p style="margin-top:8px;">Our proposed solution leverages Hala's extensive logistics infrastructure across the Kingdom of Saudi Arabia, with particular strength in the ${customer.region} region. We offer a comprehensive warehousing and distribution solution tailored to the specific needs of the ${customer.industry} sector.</p>
          <p style="margin-top:8px;">The estimated annual value of this engagement is <strong>${formatSAR(workspace.estimatedValue)}</strong>, with a projected gross margin of <strong>${formatPercent(workspace.gpPercent)}</strong>.</p>
        </div>
      `)}

      ${generateSection("Scope of Work", `
        <div style="font-size:11px;color:#555;line-height:1.7;">
          <ol style="padding-left:20px;">
            <li style="margin-bottom:6px;">Receiving & Inbound Quality Inspection</li>
            <li style="margin-bottom:6px;">Putaway & Storage Management</li>
            <li style="margin-bottom:6px;">Inventory Management & Cycle Counting</li>
            <li style="margin-bottom:6px;">Order Processing & Pick/Pack</li>
            <li style="margin-bottom:6px;">Dispatch & Outbound Loading</li>
            <li style="margin-bottom:6px;">Returns Management</li>
            <li style="margin-bottom:6px;">Value Added Services (VAS)</li>
            <li style="margin-bottom:6px;">Reporting & KPI Dashboard Access</li>
          </ol>
        </div>
      `)}

      ${generateSection("Workspace Details", generateKVGrid([
        { label: "Current Stage", value: getStageLabel(workspace.stage) },
        { label: "Estimated Value", value: formatSAR(workspace.estimatedValue) },
        { label: "Pallet Volume", value: workspace.palletVolume.toLocaleString() },
        { label: "GP%", value: formatPercent(workspace.gpPercent) },
        { label: "CRM Deal", value: workspace.crmDealId || "N/A" },
        { label: "Account Owner", value: workspace.owner },
      ]))}
    </div>
    ${generateFooter("Proposal Document")}
  `);
}

export function generatePnLPDF(workspace: Workspace, customer: Customer, quote: Quote): string {
  const annualCost = quote.totalCost;
  const annualRevenue = quote.annualRevenue;
  const grossProfit = annualRevenue - annualCost;
  const facilityCost = annualCost * 0.35;
  const staffCost = annualCost * 0.30;
  const mheCost = annualCost * 0.10;
  const insuranceCost = annualCost * 0.05;
  const opsCost = annualCost * 0.10;
  const gaCost = annualCost * 0.10;

  return wrapDocument(`
    ${generateHeader("Profit & Loss Summary", `${customer.name} — ${workspace.title}`, `PNL-${workspace.id.toUpperCase()}`)}
    <div style="padding:32px;">
      ${generateSection("Deal Overview", generateKVGrid([
        { label: "Customer", value: customer.name },
        { label: "Facility", value: customer.facility },
        { label: "Service Type", value: customer.serviceType },
        { label: "Pallet Volume", value: quote.palletVolume.toLocaleString() },
        { label: "Contract Value", value: formatSAR(annualRevenue) },
        { label: "GP%", value: formatPercent(quote.gpPercent) },
      ]))}

      ${generateSection("Revenue Breakdown", generateTable(
        ["Revenue Line", "Monthly", "Annual", "% of Total"],
        [
          ["Storage Revenue", formatSAR(quote.storageRate * quote.palletVolume * 30), formatSAR(quote.storageRate * quote.palletVolume * 30 * 12), `${((quote.storageRate * quote.palletVolume * 30 * 12 / annualRevenue) * 100).toFixed(1)}%`],
          ["Inbound Handling", formatSAR(quote.inboundRate * quote.palletVolume), formatSAR(quote.inboundRate * quote.palletVolume * 12), `${((quote.inboundRate * quote.palletVolume * 12 / annualRevenue) * 100).toFixed(1)}%`],
          ["Outbound Handling", formatSAR(quote.outboundRate * quote.palletVolume), formatSAR(quote.outboundRate * quote.palletVolume * 12), `${((quote.outboundRate * quote.palletVolume * 12 / annualRevenue) * 100).toFixed(1)}%`],
          ["<strong>Total Revenue</strong>", `<strong>${formatSAR(quote.monthlyRevenue)}</strong>`, `<strong>${formatSAR(annualRevenue)}</strong>`, "<strong>100%</strong>"],
        ]
      ))}

      ${generateSection("Cost Breakdown", generateTable(
        ["Cost Category", "Annual Cost", "% of OPEX"],
        [
          ["Facility Rent & Utilities", formatSAR(facilityCost), "35%"],
          ["Staff & Labor", formatSAR(staffCost), "30%"],
          ["MHE (Purchase/Rental)", formatSAR(mheCost), "10%"],
          ["Insurance", formatSAR(insuranceCost), "5%"],
          ["Operational Costs", formatSAR(opsCost), "10%"],
          ["G&A (10% of OPEX)", formatSAR(gaCost), "10%"],
          ["<strong>Total OPEX</strong>", `<strong>${formatSAR(annualCost)}</strong>`, "<strong>100%</strong>"],
        ]
      ))}

      ${generateSection("Profitability Summary", generateKVGrid([
        { label: "Annual Revenue", value: formatSAR(annualRevenue) },
        { label: "Total OPEX", value: formatSAR(annualCost) },
        { label: "Gross Profit", value: formatSAR(grossProfit) },
        { label: "GP%", value: formatPercent(quote.gpPercent) },
        { label: "Monthly Revenue", value: formatSAR(quote.monthlyRevenue) },
        { label: "Monthly Profit", value: formatSAR(grossProfit / 12) },
      ], 3))}

      <div style="padding:16px;background:#fff8e1;border:1px solid #ffe082;border-radius:6px;font-size:11px;color:#795548;margin-top:16px;">
        <strong>Approval Note:</strong> GP% of ${formatPercent(quote.gpPercent)} ${quote.gpPercent >= 22 ? "meets the standard threshold." : quote.gpPercent >= 10 ? "is below the 22% threshold — Director approval required." : "is below 10% — CEO/CFO approval required."}
      </div>
    </div>
    ${generateFooter("P&L Summary")}
  `);
}

export function generateECRScorecardPDF(customer: Customer): string {
  const growthScore = customer.grade === "A" ? 0.8 : customer.grade === "B" ? 0.6 : customer.grade === "C" ? 0.4 : 0.2;
  const acquisitionScore = customer.grade === "A" ? 0.9 : customer.grade === "B" ? 0.7 : customer.grade === "C" ? 0.5 : 0.3;
  const ecr = calculateECR(customer.dso, customer.contractValue2025, 25, growthScore, acquisitionScore);

  let dsoScore = 0;
  if (customer.dso <= 30) dsoScore = 1.0;
  else if (customer.dso <= 45) dsoScore = 0.5;
  else dsoScore = 0.0;

  let cvScore = 0;
  if (customer.contractValue2025 > 2000000) cvScore = 1.0;
  else if (customer.contractValue2025 > 1000000) cvScore = 0.7;
  else if (customer.contractValue2025 > 500000) cvScore = 0.3;
  else if (customer.contractValue2025 > 100000) cvScore = 0.2;
  else cvScore = 0.0;

  return wrapDocument(`
    ${generateHeader("Customer Classification Scorecard", customer.name, `ECR-${customer.code}`)}
    <div style="padding:32px;">
      ${generateSection("Customer Profile", generateKVGrid([
        { label: "Customer Name", value: customer.name },
        { label: "Code", value: customer.code },
        { label: "Group", value: customer.group },
        { label: "Region", value: `${customer.city}, ${customer.region}` },
        { label: "Industry", value: customer.industry },
        { label: "Status", value: customer.status },
        { label: "Service Type", value: customer.serviceType },
        { label: "Account Owner", value: customer.accountOwner },
        { label: "Facility", value: customer.facility },
      ]))}

      ${generateSection("ECR Score Breakdown", generateTable(
        ["Criteria", "Weight", "Raw Value", "Score", "Weighted"],
        [
          ["DSO (Days Sales Outstanding)", "30%", `${customer.dso} days`, dsoScore.toFixed(1), (dsoScore * 0.30 * 100).toFixed(1) + "%"],
          ["Contract Value", "30%", formatSAR(customer.contractValue2025), cvScore.toFixed(1), (cvScore * 0.30 * 100).toFixed(1) + "%"],
          ["Client Profitability (GP%)", "20%", "Calculated", "—", "—"],
          ["Potential Growth", "10%", "Assessed", growthScore.toFixed(1), (growthScore * 0.10 * 100).toFixed(1) + "%"],
          ["Cost of Acquisition", "10%", "Assessed", acquisitionScore.toFixed(1), (acquisitionScore * 0.10 * 100).toFixed(1) + "%"],
          [`<strong>Total ECR Score</strong>`, "<strong>100%</strong>", "", "", `<strong>${ecr.score.toFixed(1)}%</strong>`],
        ]
      ))}

      <div style="text-align:center;padding:24px;margin:16px 0;">
        <div style="display:inline-block;width:80px;height:80px;border-radius:50%;background:${ecr.grade === "A" ? "#22c55e" : ecr.grade === "B" ? "#3b82f6" : ecr.grade === "C" ? "#f59e0b" : ecr.grade === "D" ? "#f97316" : "#ef4444"};color:white;font-size:36px;font-weight:700;line-height:80px;font-family:'Source Serif 4',Georgia,serif;">${ecr.grade}</div>
        <div style="font-size:14px;font-weight:600;margin-top:8px;color:${HALA_NAVY};">Grade: ${ecr.grade} (${ecr.score.toFixed(1)}%)</div>
      </div>

      ${generateSection("Financial Performance", generateKVGrid([
        { label: "Revenue 2023", value: formatSAR(customer.revenue2023) },
        { label: "Revenue 2024", value: formatSAR(customer.revenue2024) },
        { label: "Revenue 2025 YTD", value: formatSAR(customer.revenue2025) },
        { label: "Contract Value 2025", value: formatSAR(customer.contractValue2025) },
        { label: "DSO", value: `${customer.dso} days` },
        { label: "Payment Status", value: customer.paymentStatus },
      ]))}

      ${generateSection("Capacity Utilization", generateKVGrid([
        { label: "Pallets Contracted", value: customer.palletContracted.toLocaleString() },
        { label: "Pallets Occupied", value: customer.palletOccupied.toLocaleString() },
        { label: "Utilization Rate", value: customer.palletContracted > 0 ? formatPercent((customer.palletOccupied / customer.palletContracted) * 100) : "N/A" },
        { label: "Growth Potential", value: customer.palletPotential.toLocaleString() + " pallets" },
        { label: "Rate Per Pallet", value: `SAR ${customer.ratePerPallet}/day` },
        { label: "Contract Expiry", value: customer.contractExpiry },
      ]))}

      ${generateSection("Grade Scale Reference", generateTable(
        ["Grade", "Score Range", "Description"],
        [
          ["A", "90–100%", "Premium client — strategic priority, full service commitment"],
          ["B", "80–89%", "Strong client — maintain and grow relationship"],
          ["C", "70–79%", "Standard client — monitor performance, seek improvement"],
          ["D", "60–69%", "At-risk client — review terms, consider restructuring"],
          ["F", "Below 60%", "Underperforming — escalate for management review"],
        ]
      ))}
    </div>
    ${generateFooter("ECR Scorecard")}
  `);
}

export function generateSLAPDF(workspace: Workspace, customer: Customer): string {
  return wrapDocument(`
    ${generateHeader("Service Level Agreement", `${customer.name} — ${workspace.title}`, `SLA-${workspace.id.toUpperCase()}`)}
    <div style="padding:32px;">
      ${generateSection("Agreement Overview", generateKVGrid([
        { label: "Client", value: customer.name },
        { label: "Service Type", value: customer.serviceType },
        { label: "Facility", value: customer.facility },
        { label: "Region", value: `${customer.city}, ${customer.region}` },
        { label: "Effective Date", value: "Upon signature" },
        { label: "Review Period", value: "Quarterly" },
      ]))}

      ${generateSection("Key Performance Indicators", generateTable(
        ["KPI", "Target", "Measurement", "Penalty Trigger"],
        [
          ["Inbound Processing Time", "< 4 hours", "Time from dock receipt to putaway", "> 6 hours"],
          ["Order Accuracy", "> 99.5%", "Correct items picked / Total items", "< 99%"],
          ["On-Time Dispatch", "> 98%", "Orders dispatched on time / Total orders", "< 95%"],
          ["Inventory Accuracy", "> 99.8%", "Cycle count accuracy", "< 99.5%"],
          ["Damage Rate", "< 0.1%", "Damaged units / Total units handled", "> 0.3%"],
          ["Space Utilization", "> 85%", "Occupied pallets / Contracted pallets", "< 75%"],
          ["Customer Response Time", "< 2 hours", "Time to respond to client queries", "> 4 hours"],
          ["Reporting Timeliness", "100%", "Reports delivered on schedule", "Any delay"],
        ]
      ))}

      ${generateSection("Service Scope", `
        <div style="font-size:11px;color:#555;line-height:1.7;">
          <ol style="padding-left:20px;">
            <li style="margin-bottom:6px;"><strong>Receiving & Inspection:</strong> Unloading, quality inspection, and documentation of all inbound shipments.</li>
            <li style="margin-bottom:6px;"><strong>Storage Management:</strong> Systematic putaway, location management, and environmental control.</li>
            <li style="margin-bottom:6px;"><strong>Inventory Control:</strong> Real-time WMS tracking, cycle counting, and reconciliation.</li>
            <li style="margin-bottom:6px;"><strong>Order Fulfillment:</strong> Pick, pack, and dispatch per client specifications.</li>
            <li style="margin-bottom:6px;"><strong>Returns Processing:</strong> Inspection, grading, and restocking of returned goods.</li>
            <li style="margin-bottom:6px;"><strong>Reporting:</strong> Daily, weekly, and monthly operational reports via client portal.</li>
          </ol>
        </div>
      `)}

      ${generateSection("Escalation Matrix", generateTable(
        ["Level", "Trigger", "Response Time", "Contact"],
        [
          ["Level 1", "Operational issue", "< 2 hours", "Warehouse Supervisor"],
          ["Level 2", "Service failure", "< 4 hours", "Operations Manager"],
          ["Level 3", "SLA breach", "< 8 hours", "Regional Operations Head"],
          ["Level 4", "Critical failure", "Immediate", "Operations Director"],
        ]
      ))}
    </div>
    ${generateFooter("SLA Document")}
  `);
}

// ============================================================
// PDF GENERATION (Browser Print)
// ============================================================

function wrapDocument(content: string): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&family=Source+Serif+4:wght@400;600;700&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'IBM Plex Sans', -apple-system, sans-serif; font-size: 12px; color: #333; line-height: 1.5; }
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          @page { margin: 0; size: A4; }
        }
      </style>
    </head>
    <body>
      ${content}
    </body>
    </html>
  `;
}

export function openPDFPreview(htmlContent: string, title: string): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to generate PDFs");
    return;
  }
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.document.title = title;
  // Auto-trigger print dialog after a brief delay for rendering
  setTimeout(() => {
    printWindow.print();
  }, 500);
}

// Export types for the document engine
export type PDFDocumentType = "quote" | "proposal" | "pnl" | "ecr_scorecard" | "sla";

export interface PDFGenerationResult {
  success: boolean;
  documentType: PDFDocumentType;
  title: string;
  error?: string;
}
