/**
 * SUPA-003B: Seed proposals, negotiations, SLA drafts/sections/kpis/gaps,
 * activity events, and audit events with full frontend-parity data.
 */
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
dotenv.config();

const url = process.env.SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const sb = createClient(url, key, { auth: { persistSession: false } });

async function upsert(table: string, rows: any[]) {
  const { error } = await sb.from(table).upsert(rows, { onConflict: 'id' });
  if (error) console.error(`[${table}]`, error.message);
  else console.log(`✅ ${table}: ${rows.length} rows`);
}

async function main() {
  // ── Proposals ──
  await upsert('commercial_proposal_versions', [
    { id:'prop-v01', workspace_id:'w4', scenario_id:'qs-a', version:'v0.1', status:'Drafting', proposal_name:'Al-Rajhi Emergency Storage Proposal', linked_quote_scenario_name:'Option A — Standard Tariff', proposal_type:'Internal Draft', client_facing:false, client_facing_mock:false, revenue:1200000, gp_percent:8.5, margin_delta_from_quote:0, margin_delta:'0%', owner:'Amin Al-Rashid', review_status:'Needs Commercial Review', future_gate:'Would Require Review in Production', future_gate_status:'Would Require Review in Production', mock_escalation_status:'Red — Margin below threshold', issued_at_mock:'', last_updated:'2026-05-02', notes:'Low GP and customer score require review before client-facing proposal in production.' },
    { id:'prop-v02', workspace_id:'w4', scenario_id:'qs-c', version:'v0.2', status:'Client-Facing Draft Mock', proposal_name:'Al-Rajhi Emergency Storage Proposal', linked_quote_scenario_name:'Option C — Premium Fast Implementation', proposal_type:'Client-Facing Mock', client_facing:true, client_facing_mock:true, revenue:1380000, gp_percent:21.7, margin_delta_from_quote:0, margin_delta:'0%', owner:'Amin Al-Rashid', review_status:'Needs Ops Review', future_gate:'Future Gate Warning', future_gate_status:'Future Gate Warning', mock_escalation_status:'Amber — Near threshold', issued_at_mock:'2026-05-02', last_updated:'2026-05-02', notes:'Better option but near margin threshold. Ops capacity confirmation needed.' },
    { id:'prop-v03', workspace_id:'w4', scenario_id:'qs-b', version:'v0.3', status:'Negotiation Round Active', proposal_name:'Al-Rajhi Emergency Storage Proposal', linked_quote_scenario_name:'Option B — Aggressive Entry Price', proposal_type:'Negotiation Response', client_facing:true, client_facing_mock:true, revenue:1080000, gp_percent:5.6, margin_delta_from_quote:-2.9, margin_delta:'-2.9%', owner:'Amin Al-Rashid', review_status:'Future Approval Required', future_gate:'Would Require Review in Production', future_gate_status:'Would Require Review in Production', mock_escalation_status:'Critical — Executive review required', issued_at_mock:'2026-05-02', last_updated:'2026-05-02', notes:'Client requested lower price; production would require executive review.' },
  ]);

  // ── Negotiations ──
  await upsert('commercial_negotiation_rounds', [
    { id:'neg-r1', workspace_id:'w4', proposal_version_id:'prop-v01', round_number:1, client_ask:'Emergency storage availability and fast start for 4,800 pallets', hala_response:'Standard tariff with emergency surcharge; 4-6 week onboarding', pricing_change:'None', margin_change:'0%', concession_reason:'N/A — initial request', approval_impact:'None — standard terms', status:'Responded Mock', owner:'Amin Al-Rashid', last_updated:'2026-05-01', notes:'Client accepted scope but requested pricing review.' },
    { id:'neg-r2', workspace_id:'w4', proposal_version_id:'prop-v03', round_number:2, client_ask:'Discount on storage rate — SAR 169.50 too high for emergency allocation', hala_response:'Revised to aggressive entry pricing with reduced storage rate; GP drops to 5.6%', pricing_change:'Storage rate reduced from SAR 180 to SAR 155/plt/mo', margin_change:'-2.9% GP (8.5% → 5.6%)', concession_reason:'Client price sensitivity; competitor pressure on storage rates', approval_impact:'Red: future production would require CEO/CFO sign-off', status:'Revised Proposal Needed', owner:'Amin Al-Rashid', last_updated:'2026-05-02', notes:'GP critically low. Reprice or walk away recommended.' },
    { id:'neg-r3', workspace_id:'w4', proposal_version_id:'prop-v02', round_number:3, client_ask:'Fast implementation with premium service; accept higher rate if onboarding < 3 weeks', hala_response:'Premium fast implementation proposal at SAR 210/plt/mo; GP 21.7%', pricing_change:'Premium rate applied (SAR 210 vs SAR 180 standard)', margin_change:'+13.2% GP (8.5% → 21.7%)', concession_reason:'N/A — client accepts premium for speed', approval_impact:'Amber: Commercial/Ops review recommended', status:'Awaiting Client', owner:'Amin Al-Rashid', last_updated:'2026-05-02', notes:'Best commercial outcome. Client reviewing internally.' },
  ]);

  // ── SLA Drafts ──
  await upsert('commercial_sla_drafts', [
    { id:'sla-v01', workspace_id:'w4', version:'v0.1', linked_scenario:'qs-a', status:'Pricing Lock Warning', sla_name:'Al-Rajhi Emergency Storage SLA', linked_proposal_id:'prop-v01', linked_proposal_name:'Proposal v0.1 — Internal Draft', linked_quote_scenario_id:'qs-a', linked_quote_scenario_name:'Option A — Standard Tariff', sla_type:'Emergency Storage SLA', client_facing_mock:false, pricing_lock_status:'Not Locked', commercial_terms_status:'Linked to Proposal Mock', ops_review:'Needs Ops Review', ops_review_status:'Needs Ops Review', legal_review:'Not Reviewed', legal_review_status:'Not Reviewed', kpi_readiness:45, responsibility_readiness:55, escalation_matrix_status:'Draft Mock', promise_gap_count:3, risk_level:'High', future_gate_status:'Would Require Review in Production', mock_escalation_status:'Red — Pricing not locked', owner:'Amin Al-Rashid', last_updated:'2026-05-02', notes:'SLA should not be client-facing until pricing and ops assumptions are reviewed.',
      sections: JSON.stringify([
        {id:'sec-1',title:'Service Scope',status:'Draft Mock'},{id:'sec-2',title:'Operating Hours',status:'Draft Mock'},{id:'sec-3',title:'KPI Framework',status:'Draft Mock'},{id:'sec-4',title:'Reporting Cadence',status:'Draft Mock'},{id:'sec-5',title:'Escalation Matrix',status:'Draft Mock'},{id:'sec-6',title:'Responsibilities',status:'Draft Mock'},{id:'sec-7',title:'Commercial Terms',status:'Pricing Lock Warning'},{id:'sec-8',title:'Legal Terms',status:'Not Started'},{id:'sec-9',title:'Handover / Onboarding',status:'Draft Mock'},{id:'sec-10',title:'Exclusions',status:'Draft Mock'}
      ]),
      kpis: JSON.stringify([
        {id:'kpi-1',name:'Inbound Receiving',target:'< 4 hours from truck arrival',method:'WMS timestamp',readiness:60,risk:'Medium'},
        {id:'kpi-2',name:'Put-Away Completion',target:'Same-day for standard SKUs',method:'WMS put-away event',readiness:50,risk:'High'},
        {id:'kpi-3',name:'Inventory Accuracy',target:'> 99.5%',method:'Cycle count reconciliation',readiness:70,risk:'Low'},
        {id:'kpi-4',name:'Order Dispatch Readiness',target:'< 24 hours from order release',method:'WMS dispatch event',readiness:45,risk:'Medium'},
        {id:'kpi-5',name:'Reporting Cadence',target:'Monthly report + weekly flash',method:'Report delivery confirmation',readiness:65,risk:'Low'},
        {id:'kpi-6',name:'Customer Escalation Response',target:'< 2 hours for critical',method:'Ticket timestamp',readiness:40,risk:'High'},
        {id:'kpi-7',name:'First Billing Readiness',target:'Within 30 days of go-live',method:'Finance billing trigger',readiness:30,risk:'High'}
      ]),
      promise_gaps: JSON.stringify([
        {id:'gap-1',promise:'Standard inbound receiving < 4 hours',reality:'Special handling may take 6-8 hours',impact:'KPI breach risk on day 1',severity:'High',action:'Add special handling exception to SLA'},
        {id:'gap-2',promise:'400 pallet positions allocated',reality:'Effective required 450-480 with constraints',impact:'Capacity shortfall',severity:'High',action:'Validate effective position requirement'},
        {id:'gap-3',promise:'Pricing not locked but SLA implies fixed commitment',reality:'Pricing may change after negotiation',impact:'Commercial risk',severity:'Critical',action:'Lock pricing before finalizing SLA'}
      ])
    },
    { id:'sla-v02', workspace_id:'w4', version:'v0.2', linked_scenario:'qs-c', status:'Linked to Commercial Terms Mock', sla_name:'Al-Rajhi Emergency Storage SLA', linked_proposal_id:'prop-v02', linked_proposal_name:'Proposal v0.2 — Client-Facing Draft Mock', linked_quote_scenario_id:'qs-c', linked_quote_scenario_name:'Option C — Premium Fast Implementation', sla_type:'Emergency Storage SLA', client_facing_mock:true, pricing_lock_status:'Mock Linked', commercial_terms_status:'Linked to Proposal Mock', ops_review:'Needs Ops Review', ops_review_status:'Needs Ops Review', legal_review:'Needs Legal Review', legal_review_status:'Needs Legal Review', kpi_readiness:72, responsibility_readiness:70, escalation_matrix_status:'Draft Mock', promise_gap_count:1, risk_level:'Medium', future_gate_status:'Future Gate Warning', mock_escalation_status:'Amber — Ops/Legal review pending', owner:'Amin Al-Rashid', last_updated:'2026-05-02', notes:'Better SLA basis but still needs Ops/Legal review.',
      sections:'[]', kpis:'[]', promise_gaps: JSON.stringify([{id:'gap-6',promise:'Premium service with < 3 week onboarding',reality:'Ops capacity not confirmed; standard is 4-6 weeks',impact:'Client expectation mismatch',severity:'Medium',action:'Confirm Ops allocation'}])
    },
    { id:'sla-v03', workspace_id:'w4', version:'v0.3', linked_scenario:'qs-b', status:'Ops Review Needed', sla_name:'Al-Rajhi Emergency Storage SLA', linked_proposal_id:'prop-v03', linked_proposal_name:'Proposal v0.3 — Negotiation Response Mock', linked_quote_scenario_id:'qs-b', linked_quote_scenario_name:'Option B — Aggressive Entry Price', sla_type:'Emergency Storage SLA', client_facing_mock:true, pricing_lock_status:'Future Lock Required', commercial_terms_status:'Future Approval Required', ops_review:'Needs Ops Review', ops_review_status:'Needs Ops Review', legal_review:'Needs Legal Review', legal_review_status:'Needs Legal Review', kpi_readiness:35, responsibility_readiness:40, escalation_matrix_status:'Not Reviewed', promise_gap_count:4, risk_level:'Critical', future_gate_status:'Would Require Review in Production', mock_escalation_status:'Critical — Executive review required', owner:'Amin Al-Rashid', last_updated:'2026-05-02', notes:'Production would require executive/commercial/legal review.',
      sections:'[]', kpis:'[]', promise_gaps: JSON.stringify([
        {id:'gap-4',promise:'Fast implementation < 3 weeks',reality:'QC/shift setup typically 4-6 weeks',impact:'Onboarding timeline breach',severity:'High',action:'Confirm Ops capacity'},
        {id:'gap-5',promise:'LFS system integration',reality:'Manual put-away risk if not configured',impact:'Put-away KPI breach',severity:'Medium',action:'Confirm LFS configuration'},
        {id:'gap-7',promise:'Aggressive pricing implies standard service',reality:'Low GP limits operational investment',impact:'SLA promises exceed margin capacity',severity:'High',action:'Revise SLA scope or reprice'},
        {id:'gap-8',promise:'24/7 escalation support',reality:'Shift coverage may not include overnight',impact:'Escalation response breach',severity:'High',action:'Confirm shift coverage'}
      ])
    },
  ]);

  // ── Activity Events ──
  const actEvents = [
    {id:'act-01',workspace_id:'w4',event_type:'workspace_opened',title:'Commercial workspace opened',description:'Al-Rajhi Emergency Storage workspace opened for quoting.',category:'Workspace',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T08:30:00Z',severity:'Info',related_artifact:'',related_module:'Workspace',related_scenario_id:'',mock:true,action:'Commercial workspace opened',detail:'Al-Rajhi Emergency Storage workspace opened for quoting.'},
    {id:'act-02',workspace_id:'w4',event_type:'quote_control_opened',title:'Quote Control opened',description:'Quote Control tab accessed. 3 scenarios available.',category:'Quote',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T08:35:00Z',severity:'Info',related_artifact:'',related_module:'Quote Control',related_scenario_id:'',mock:true,action:'Quote Control opened',detail:'Quote Control tab accessed. 3 scenarios available.'},
    {id:'act-03',workspace_id:'w4',event_type:'scenario_selected',title:'Option A — Standard Tariff selected',description:'Standard tariff scenario selected for review. GP 8.5%.',category:'Quote',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T08:40:00Z',severity:'Info',related_artifact:'Option A',related_module:'Quote Control',related_scenario_id:'qs-a',mock:true,action:'Option A — Standard Tariff selected',detail:'Standard tariff scenario selected for review. GP 8.5%.'},
    {id:'act-04',workspace_id:'w4',event_type:'pricing_lines_viewed',title:'Pricing lines reviewed',description:'7 pricing lines reviewed for Option A.',category:'Pricing',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T09:00:00Z',severity:'Info',related_artifact:'Option A',related_module:'Pricing Lines',related_scenario_id:'qs-a',mock:true,action:'Pricing lines reviewed',detail:'7 pricing lines reviewed for Option A.'},
    {id:'act-05',workspace_id:'w4',event_type:'low_margin_flagged',title:'Low-margin line flagged',description:'Storage line GP 5.2% — below 10% threshold.',category:'Margin',actor:'System',role:'Mock Engine',timestamp:'2026-04-28T09:05:00Z',severity:'High',related_artifact:'Option A — Storage',related_module:'Pricing Lines',related_scenario_id:'qs-a',mock:true,action:'Low-margin line flagged',detail:'Storage line GP 5.2% — below 10% threshold.'},
    {id:'act-06',workspace_id:'w4',event_type:'pnl_reviewed',title:'P&L snapshot reviewed',description:'P&L snapshot for Option A reviewed. Revenue SAR 1.20M, GP 8.5%.',category:'P&L',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T09:15:00Z',severity:'Info',related_artifact:'Option A',related_module:'P&L Snapshot',related_scenario_id:'qs-a',mock:true,action:'P&L snapshot reviewed',detail:'P&L snapshot for Option A reviewed.'},
    {id:'act-07',workspace_id:'w4',event_type:'margin_authority_evaluated',title:'Margin authority evaluated',description:'GP 8.5% below 10% threshold. CEO/CFO approval authority required.',category:'Margin',actor:'System',role:'Mock Engine',timestamp:'2026-04-28T09:20:00Z',severity:'High',related_artifact:'Option A',related_module:'Margin Authority',related_scenario_id:'qs-a',mock:true,action:'Margin authority evaluated',detail:'GP 8.5% below 10% threshold.'},
    {id:'act-08',workspace_id:'w4',event_type:'customer_score_reviewed',title:'Customer score reviewed',description:'Al-Rajhi Steel ECR grade: C-.',category:'Customer Score',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T10:00:00Z',severity:'Warning',related_artifact:'Al-Rajhi Steel',related_module:'Customer Score',related_scenario_id:'qs-a',mock:true,action:'Customer score reviewed',detail:'Al-Rajhi Steel ECR grade: C-.'},
    {id:'act-09',workspace_id:'w4',event_type:'capacity_reviewed',title:'Capacity fit reviewed',description:'Warehouse capacity 78% utilized.',category:'Capacity',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T10:30:00Z',severity:'Warning',related_artifact:'Option A',related_module:'Capacity Fit',related_scenario_id:'qs-a',mock:true,action:'Capacity fit reviewed',detail:'Warehouse capacity 78% utilized.'},
    {id:'act-10',workspace_id:'w4',event_type:'escalation_created',title:'Mock escalation created',description:'Red: Margin below threshold for Option A.',category:'Escalation',actor:'System',role:'Mock Engine',timestamp:'2026-04-29T10:00:00Z',severity:'High',related_artifact:'Option A',related_module:'Mock Escalation',related_scenario_id:'qs-a',mock:true,action:'Mock escalation created',detail:'Red: Margin below threshold for Option A.'},
    {id:'act-11',workspace_id:'w4',event_type:'proposal_created',title:'Proposal v0.1 created',description:'Internal draft proposal created linked to Option A.',category:'Proposal',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-30T08:00:00Z',severity:'Info',related_artifact:'Proposal v0.1',related_module:'Proposal Control',related_scenario_id:'qs-a',mock:true,action:'Proposal v0.1 created',detail:'Internal draft proposal created.'},
    {id:'act-12',workspace_id:'w4',event_type:'sla_pricing_lock',title:'SLA pricing lock warning',description:'SLA v0.1 pricing not locked.',category:'SLA',actor:'System',role:'Mock Engine',timestamp:'2026-05-02T08:00:00Z',severity:'High',related_artifact:'SLA v0.1',related_module:'SLA Control',related_scenario_id:'qs-a',mock:true,action:'SLA pricing lock warning',detail:'SLA v0.1 pricing not locked.'},
  ];
  await upsert('commercial_activity_events', actEvents);

  // ── Audit Events ──
  const audEvents = [
    {id:'aud-01',workspace_id:'w4',event_code:'WORKSPACE_OPENED_MOCK',event_name:'Workspace Opened',description:'Commercial workspace opened.',category:'WORKSPACE',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T08:30:00Z',entity_type:'Workspace',entity_id:'w4',entity_name:'Al-Rajhi Emergency Storage',before_state:'—',after_state:'Open',mock:true,severity:'Info',trace_id:'tr-001',action:'Workspace Opened',detail:'Commercial workspace opened.'},
    {id:'aud-02',workspace_id:'w4',event_code:'QUOTE_CONTROL_OPENED',event_name:'Quote Control Opened',description:'Quote Control tab accessed.',category:'QUOTE',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T08:35:00Z',entity_type:'Quote Control',entity_id:'',entity_name:'Commercial Workspace',before_state:'—',after_state:'Opened',mock:true,severity:'Info',trace_id:'tr-002',action:'Quote Control Opened',detail:'Quote Control tab accessed.'},
    {id:'aud-03',workspace_id:'w4',event_code:'QUOTE_SCENARIO_SELECTED',event_name:'Scenario Selected',description:'Option A selected. GP 8.5%.',category:'QUOTE',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-28T08:40:00Z',entity_type:'Quote Scenario',entity_id:'qs-a',entity_name:'Option A — Standard Tariff',before_state:'None',after_state:'Selected',mock:true,severity:'Info',trace_id:'tr-003',action:'Scenario Selected',detail:'Option A selected.'},
    {id:'aud-04',workspace_id:'w4',event_code:'LOW_MARGIN_LINE_FLAGGED',event_name:'Low Margin Flagged',description:'Storage line GP 5.2% below 10% threshold.',category:'MARGIN',actor:'System',role:'Mock Engine',timestamp:'2026-04-28T09:05:00Z',entity_type:'Pricing Line',entity_id:'pl-a1',entity_name:'Storage — Base Rate',before_state:'5.2% GP',after_state:'Flagged',mock:true,severity:'High',trace_id:'tr-005',action:'Low Margin Flagged',detail:'Storage line GP 5.2% below 10%.'},
    {id:'aud-05',workspace_id:'w4',event_code:'MARGIN_AUTHORITY_EVALUATED',event_name:'Margin Authority Evaluated',description:'GP 8.5% requires CEO/CFO approval.',category:'MARGIN',actor:'System',role:'Mock Engine',timestamp:'2026-04-28T09:20:00Z',entity_type:'Margin Authority',entity_id:'qs-a',entity_name:'Option A',before_state:'8.5% GP',after_state:'CEO/CFO Required',mock:true,severity:'High',trace_id:'tr-007',action:'Margin Authority Evaluated',detail:'GP 8.5% requires CEO/CFO approval.'},
    {id:'aud-06',workspace_id:'w4',event_code:'MOCK_ESCALATION_CREATED',event_name:'Mock Escalation Created',description:'Red: Margin below threshold.',category:'ESCALATION',actor:'System',role:'Mock Engine',timestamp:'2026-04-29T10:00:00Z',entity_type:'Mock Escalation',entity_id:'qs-a',entity_name:'Option A Margin',before_state:'No Escalation',after_state:'Red — CEO/CFO',mock:true,severity:'High',trace_id:'tr-013',action:'Mock Escalation Created',detail:'Red: Margin below threshold.'},
    {id:'aud-07',workspace_id:'w4',event_code:'PROPOSAL_VERSION_SELECTED',event_name:'Proposal Created',description:'Proposal v0.1 internal draft created.',category:'PROPOSAL',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-04-30T08:00:00Z',entity_type:'Proposal',entity_id:'prop-v01',entity_name:'Proposal v0.1',before_state:'None',after_state:'Drafting',mock:true,severity:'Info',trace_id:'tr-015',action:'Proposal Created',detail:'Proposal v0.1 internal draft created.'},
    {id:'aud-08',workspace_id:'w4',event_code:'NEGOTIATION_ROUND_LOGGED',event_name:'Negotiation Round Logged',description:'Round 2: Client discount request. GP drops to 5.6%.',category:'NEGOTIATION',actor:'Amin Al-Rashid',role:'Commercial Director',timestamp:'2026-05-01T08:00:00Z',entity_type:'Negotiation',entity_id:'neg-r2',entity_name:'Round 2',before_state:'8.5% GP',after_state:'5.6% GP',mock:true,severity:'Critical',trace_id:'tr-016',action:'Negotiation Round Logged',detail:'Round 2: Client discount request.'},
    {id:'aud-09',workspace_id:'w4',event_code:'SLA_PRICING_LOCK_WARNING',event_name:'SLA Pricing Lock Warning',description:'SLA v0.1 pricing not locked.',category:'SLA',actor:'System',role:'Mock Engine',timestamp:'2026-05-02T08:05:00Z',entity_type:'SLA',entity_id:'sla-v01',entity_name:'SLA v0.1',before_state:'Not Locked',after_state:'Warning Shown',mock:true,severity:'High',trace_id:'tr-018',action:'SLA Pricing Lock Warning',detail:'SLA v0.1 pricing not locked.'},
    {id:'aud-10',workspace_id:'w4',event_code:'SLA_PROMISE_GAP_FLAGGED',event_name:'SLA Promise Gap Flagged',description:'Inbound receiving SLA < 4h vs reality 6-8h.',category:'SLA',actor:'System',role:'Mock Engine',timestamp:'2026-05-02T09:15:00Z',entity_type:'Promise Gap',entity_id:'gap-1',entity_name:'Inbound Receiving',before_state:'< 4h target',after_state:'6-8h actual',mock:true,severity:'High',trace_id:'tr-019',action:'SLA Promise Gap Flagged',detail:'Inbound receiving SLA < 4h vs reality 6-8h.'},
  ];
  await upsert('commercial_audit_events', audEvents);

  console.log('\n✅ SUPA-003B seed complete.');
}

main().catch(console.error);
