INSERT INTO tender_required_documents (id, document_name, pack_id, pack_name, category, owner, status, native_required, signed_required, stamp_required, native_status, signed_pdf_status, evidence_status, version, included_in_output, would_block_in_production, last_updated, notes) VALUES
('rd-01', 'Internal Master Working DOCX', 'tp-linde-master', 'Internal Master Pack', 'final_output', 'Amin Al-Halabi', 'draft', true, false, false, 'uploaded_mock', 'not_required', 'not_required', 3, false, false, '2026-04-28', 'Internal working document — not submitted externally.'),
('rd-02', 'Bulk Final Tender Pack PDF', 'tp-linde-bulk', 'Bulk Transportation Pack', 'final_output', 'Amin Al-Halabi', 'awaiting', true, true, true, 'missing', 'missing', 'missing', 0, true, true, '2026-04-28', 'Final compiled PDF for Bulk submission. Cannot be generated until all sections approved.'),
('rd-03', 'Bulk OBK Native Excel', 'tp-linde-bulk', 'Bulk Transportation Pack', 'pricing_obk', 'Amin Al-Halabi', 'in_review', true, false, false, 'uploaded_mock', 'not_required', 'uploaded_mock', 2, true, true, '2026-04-27', 'Native Excel required for commercial evaluation. OBK Control artifact.'),
('rd-04', 'Bulk OBK Signed/Stamped PDF', 'tp-linde-bulk', 'Bulk Transportation Pack', 'pricing_obk', 'Amin Al-Halabi', 'awaiting', false, true, true, 'not_required', 'missing', 'missing', 0, true, true, '2026-04-25', 'Signed and stamped by authorized signatory. Native Excel + signed/stamped PDF required for production submission.'),
('rd-05', 'Bulk Bid Statement Signed/Stamped PDF', 'tp-linde-bulk', 'Bulk Transportation Pack', 'bid_statement', 'Amin Al-Halabi', 'awaiting', false, true, true, 'not_required', 'missing', 'missing', 0, true, true, '2026-04-20', 'Must be signed and stamped by authorized signatory.'),
('rd-06', 'Bulk Transition Plan', 'tp-linde-bulk', 'Bulk Transportation Pack', 'transition', 'Ra''ed', 'draft', true, false, false, 'uploaded_mock', 'not_required', 'not_required', 1, true, true, '2026-04-26', ''),
('rd-07', 'Bulk Continuous Improvement Proposal Form', 'tp-linde-bulk', 'Bulk Transportation Pack', 'continuous_improvement', 'Ra''ed', 'draft', true, false, false, 'uploaded_mock', 'not_required', 'not_required', 1, true, false, '2026-04-26', ''),
('rd-08', 'Bulk Compliance Pack', 'tp-linde-bulk', 'Bulk Transportation Pack', 'compliance_pack', 'Ra''ed', 'awaiting', true, false, false, 'missing', 'not_required', 'missing', 0, true, true, '2026-04-15', 'Aggregated compliance evidence bundle.'),
('rd-09', 'PGP Final Tender Pack PDF', 'tp-linde-pgp', 'PGP Transportation Pack', 'final_output', 'Amin Al-Halabi', 'awaiting', true, true, true, 'missing', 'missing', 'missing', 0, true, true, '2026-04-28', 'Final compiled PDF for PGP submission.'),
('rd-10', 'PGP OBK Native Excel', 'tp-linde-pgp', 'PGP Transportation Pack', 'pricing_obk', 'Amin Al-Halabi', 'draft', true, false, false, 'uploaded_mock', 'not_required', 'uploaded_mock', 1, true, true, '2026-04-26', 'OBK Control artifact — native Excel for PGP pricing.'),
('rd-11', 'PGP OBK Signed/Stamped PDF', 'tp-linde-pgp', 'PGP Transportation Pack', 'pricing_obk', 'Amin Al-Halabi', 'awaiting', false, true, true, 'not_required', 'missing', 'missing', 0, true, true, '2026-04-20', 'Native Excel + signed/stamped PDF required for production submission.'),
('rd-12', 'PGP Bid Statement Signed/Stamped PDF', 'tp-linde-pgp', 'PGP Transportation Pack', 'bid_statement', 'Amin Al-Halabi', 'awaiting', false, true, true, 'not_required', 'missing', 'missing', 0, true, true, '2026-04-18', 'Must be signed and stamped by authorized signatory.'),
('rd-13', 'PGP Transition Plan', 'tp-linde-pgp', 'PGP Transportation Pack', 'transition', 'Ra''ed', 'in_review', true, false, false, 'uploaded_mock', 'not_required', 'not_required', 1, true, true, '2026-04-27', ''),
('rd-14', 'PGP Continuous Improvement Proposal Form', 'tp-linde-pgp', 'PGP Transportation Pack', 'continuous_improvement', 'Ra''ed', 'draft', true, false, false, 'uploaded_mock', 'not_required', 'not_required', 1, true, false, '2026-04-25', ''),
('rd-15', 'PGP Compliance Pack', 'tp-linde-pgp', 'PGP Transportation Pack', 'compliance_pack', 'Ra''ed', 'awaiting', true, false, false, 'missing', 'not_required', 'missing', 0, true, true, '2026-04-10', ''),
('rd-16', 'Commercial Registration Certificate', 'tp-linde-bulk', 'Bulk Transportation Pack', 'legal_registration', 'Amin Al-Halabi', 'ready', false, true, false, 'not_required', 'ready_mock', 'ready_mock', 1, true, true, '2026-04-20', 'Shared across Bulk + PGP packs.'),
('rd-17', 'VAT Certificate', 'tp-linde-bulk', 'Bulk Transportation Pack', 'legal_registration', 'Amin Al-Halabi', 'ready', false, true, false, 'not_required', 'ready_mock', 'ready_mock', 1, true, true, '2026-04-20', 'ZATCA certificate.'),
('rd-18', 'ISO 9001 / 14001 / 45001 Certificates', 'tp-linde-bulk', 'Bulk Transportation Pack', 'certification', 'Ra''ed', 'in_review', false, true, false, 'not_required', 'uploaded_mock', 'uploaded_mock', 1, true, true, '2026-04-27', 'Bundle of 3 ISO certificates. Expiry dates must be verified.'),
('rd-19', 'Insurance Certificates', 'tp-linde-bulk', 'Bulk Transportation Pack', 'insurance', 'Ra''ed', 'approved', false, true, false, 'not_required', 'ready_mock', 'ready_mock', 1, true, true, '2026-04-22', 'Motor + cargo + liability insurance bundle.'),
('rd-20', 'ADR Class 2 Certifications', 'tp-linde-bulk', 'Bulk Transportation Pack', 'hse', 'Ra''ed', 'approved', false, true, false, 'not_required', 'ready_mock', 'ready_mock', 1, true, true, '2026-04-22', 'ADR dangerous goods transport certification for cryogenic tankers.'),
('rd-21', 'Reference Credentials', 'tp-linde-bulk', 'Bulk Transportation Pack', 'fleet_operations', 'Amin Al-Halabi', 'ready', true, false, false, 'ready_mock', 'not_required', 'ready_mock', 1, true, true, '2026-04-22', 'SABIC + Aramco reference letters and contracts.'),
('rd-22', 'Performance Guarantee Confirmation', 'tp-linde-pgp', 'PGP Transportation Pack', 'pricing_obk', 'Amin Al-Halabi', 'awaiting', true, true, true, 'missing', 'missing', 'missing', 0, true, true, '2026-04-15', 'Finance must confirm performance bond structure before submission.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tender_compliance_items (id, reference, requirement, pack_id, pack_name, category, status, evidence, owner, risk_level, legal_review_required, commercial_impact, operational_impact, clarification_needed, would_block_in_production, last_updated, notes) VALUES
('ci-01', 'RFQ-3.1', 'Scope: cryogenic gases and gaseous hydrogen distribution across KSA', 'tp-linde-bulk', 'Bulk Transportation Pack', 'scope', 'compliant', 'Attached Mock', 'Amin Al-Halabi', 'low', false, 'Core scope — full alignment required', 'Fleet must cover cryogenic + gaseous', false, true, '2026-04-25', ''),
('ci-02', 'RFQ-3.2', 'Two-hub model: Dammam primary, Jeddah secondary', 'tp-linde-bulk', 'Bulk Transportation Pack', 'scope', 'compliant', 'Attached Mock', 'Ra''ed', 'low', false, 'Hub costs included in pricing', 'Operations team confirmed hub availability', false, false, '2026-04-25', ''),
('ci-03', 'RFQ-4.1', '18 x 4x2 tractors provided for cryogenic trailer operation', 'tp-linde-bulk', 'Bulk Transportation Pack', 'vehicle_specifications', 'partial', 'Pending', 'Ra''ed', 'medium', false, 'Fleet CAPEX may require adjustment', '14 available, 4 on order — delivery Q3 2026', false, true, '2026-04-27', '4 tractors on order, expected delivery before contract start.'),
('ci-04', 'RFQ-4.2', '4 x 6x4 rigid tankers provided for gaseous deliveries', 'tp-linde-bulk', 'Bulk Transportation Pack', 'vehicle_specifications', 'partial', 'Pending', 'Ra''ed', 'medium', false, 'Rigid tanker spec requires OEM confirmation', '2 available, 2 under procurement', false, true, '2026-04-27', ''),
('ci-05', 'RFQ-5.1', 'ADR Class 2 driver discipline and training compliance', 'tp-linde-bulk', 'Bulk Transportation Pack', 'adr_gdp', 'compliant', 'Attached Mock', 'Ra''ed', 'low', false, 'None', 'All assigned drivers ADR certified', false, true, '2026-04-22', ''),
('ci-06', 'RFQ-6.1', 'Linde-owned cryogenic trailer maintenance boundary acknowledged', 'tp-linde-bulk', 'Bulk Transportation Pack', 'legal_terms', 'clarification_required', 'Client Clarification Needed', 'Amin Al-Halabi', 'high', true, 'Maintenance cost boundary affects margin', 'Need to confirm which maintenance items fall on Hala vs Linde', true, true, '2026-04-28', 'Formal clarification submitted to Linde procurement. Awaiting response.'),
('ci-07', 'RFQ-7.1', 'Schedule 5 KPI regime acknowledged and accepted', 'tp-linde-bulk', 'Bulk Transportation Pack', 'kpi_pl_consequences', 'compliant', 'Attached Mock', 'Amin Al-Halabi', 'medium', false, 'KPI penalties capped at 5% monthly invoice', 'Operations must track OTIF, safety, fleet availability', false, false, '2026-04-25', ''),
('ci-08', 'RFQ-7.2', 'Schedule 6 PL consequences acknowledged', 'tp-linde-bulk', 'Bulk Transportation Pack', 'kpi_pl_consequences', 'partial', 'Pending', 'Amin Al-Halabi', 'high', true, 'Uncapped liability clause requires legal review', 'Insurance coverage must align', false, true, '2026-04-28', 'Legal team reviewing liability cap position.'),
('ci-09', 'RFQ-8.1', 'OBK pricing file completed and submitted', 'tp-linde-bulk', 'Bulk Transportation Pack', 'pricing_obk', 'non_compliant', 'Required', 'Amin Al-Halabi', 'critical', false, 'Cannot submit without completed OBK', 'None', false, true, '2026-04-28', 'OBK native Excel in review but signed/stamped version not yet available.'),
('ci-10', 'RFQ-9.1', '180-day bid validity period acknowledged', 'tp-linde-bulk', 'Bulk Transportation Pack', 'bid_validity', 'compliant', 'Attached Mock', 'Amin Al-Halabi', 'low', false, 'Pricing locked for 180 days', 'None', false, false, '2026-04-20', ''),
('ci-11', 'RFQ-10.1', '10% performance guarantee bond provided', 'tp-linde-bulk', 'Bulk Transportation Pack', 'performance_guarantee', 'clarification_required', 'Client Clarification Needed', 'Amin Al-Halabi', 'high', true, 'Bond cost impacts margin by ~0.3%', 'None', true, true, '2026-04-28', 'Finance confirming bond structure with bank.'),
('ci-12', 'RFQ-3.3', 'Multi-city packaged-gas distribution scope acknowledged', 'tp-linde-pgp', 'PGP Transportation Pack', 'scope', 'compliant', 'Attached Mock', 'Amin Al-Halabi', 'low', false, 'PGP pricing covers all listed cities', 'Route planning confirmed', false, false, '2026-04-25', ''),
('ci-13', 'RFQ-4.3', 'PGP vehicle / helper model reviewed and accepted', 'tp-linde-pgp', 'PGP Transportation Pack', 'vehicle_specifications', 'compliant', 'Attached Mock', 'Ra''ed', 'low', false, 'Helper costs included', 'Vehicle + helper model confirmed', false, false, '2026-04-25', ''),
('ci-14', 'RFQ-5.2', 'PGP GDP / safety handling requirements reviewed', 'tp-linde-pgp', 'PGP Transportation Pack', 'adr_gdp', 'partial', 'Pending', 'Ra''ed', 'medium', false, 'GDP training costs not yet budgeted', 'GDP training program under development', false, false, '2026-04-27', 'GDP handling SOP being drafted.'),
('ci-15', 'RFQ-11.1', 'PGP transition approach documented', 'tp-linde-pgp', 'PGP Transportation Pack', 'transition', 'not_reviewed', 'Not Required', 'Ra''ed', 'medium', false, 'Transition mobilization costs', '60-day transition window required', false, true, '2026-04-15', ''),
('ci-16', 'RFQ-12.1', 'PGP continuous improvement proposal required', 'tp-linde-pgp', 'PGP Transportation Pack', 'continuous_improvement', 'not_reviewed', 'Not Required', 'Ra''ed', 'low', false, 'None', 'CI plan needed', false, false, '2026-04-15', ''),
('ci-17', 'RFQ-13.1', 'Insurance certificates covering motor, cargo, and liability', 'tp-linde-bulk', 'Bulk Transportation Pack', 'insurance', 'compliant', 'Attached Mock', 'Ra''ed', 'low', false, 'Premium included in overhead', 'None', false, true, '2026-04-22', ''),
('ci-18', 'RFQ-13.2', 'Commercial Registration valid and matching entity', 'tp-linde-bulk', 'Bulk Transportation Pack', 'management_standards', 'compliant', 'Attached Mock', 'Amin Al-Halabi', 'low', false, 'None', 'None', false, true, '2026-04-20', ''),
('ci-19', 'RFQ-13.3', 'ISO 9001 / 14001 / 45001 certificates current', 'tp-linde-bulk', 'Bulk Transportation Pack', 'management_standards', 'clarification_required', 'Client Clarification Needed', 'Ra''ed', 'medium', false, 'None', 'ISO 45001 certificate expiry needs confirmation', true, true, '2026-04-27', 'ISO 45001 expiry date unclear — BSI confirmation requested.'),
('ci-20', 'RFQ-14.1', 'Separate submission emails for Bulk and PGP packs', 'tp-linde-master', 'Internal Master Pack', 'submission_format', 'non_compliant', 'Required', 'Amin Al-Halabi', 'critical', false, 'Incorrect submission format = disqualification risk', 'None', false, true, '2026-04-28', 'Submission process not yet configured for split-pack email delivery.'),
('ci-21', 'RFQ-14.2', 'Internal master pack must NOT be submitted externally', 'tp-linde-master', 'Internal Master Pack', 'submission_format', 'accepted_risk_mock', 'Not Required', 'Amin Al-Halabi', 'low', false, 'None', 'None', false, false, '2026-04-20', 'Master pack flagged as internal-only in pack config.'),
('ci-22', 'RFQ-14.3', 'Cross-pack references must be removed before submission', 'tp-linde-master', 'Internal Master Pack', 'submission_format', 'not_reviewed', 'Not Required', 'Ra''ed', 'medium', false, 'None', 'QA review required before final output', false, true, '2026-04-15', '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tender_split_checks (id, tender_workspace_id, source_pack_id, target_pack_id, check_name, description, category, status, severity, would_block_in_production, mock_resolution, notes) VALUES
('sc-01', 'tn-linde-001', 'tp-linde-master', 'tp-linde-bulk', 'Remove PGP content from Bulk output', 'All PGP-specific sections, pricing, and references must be stripped from the Bulk output pack.', 'cross_references', 'would_block', 'critical', true, 'Content filter would run automatically', ''),
('sc-02', 'tn-linde-001', 'tp-linde-master', 'tp-linde-bulk', 'Remove internal notes and draft comments', 'All internal notes, working comments, and draft markers must be removed from the external output.', 'internal_notes', 'would_block', 'high', true, 'Internal note scanner would run automatically', ''),
('sc-03', 'tn-linde-001', 'tp-linde-master', 'tp-linde-bulk', 'Check Bulk placeholders completed', 'All submission-critical placeholders for the Bulk pack must have values.', 'placeholders', 'would_block', 'critical', true, 'Placeholder register feeds this check', ''),
('sc-04', 'tn-linde-001', 'tp-linde-master', 'tp-linde-bulk', 'Check Bulk required documents ready', 'All required documents for the Bulk submission must be uploaded and approved.', 'required_documents', 'would_block', 'high', true, 'Required documents register feeds this check', ''),
('sc-05', 'tn-linde-001', 'tp-linde-master', 'tp-linde-bulk', 'Check compliance gaps resolved', 'Non-compliant and clarification-required items must be resolved before production output.', 'compliance', 'warning', 'medium', false, 'Compliance matrix feeds this check', ''),
('sc-06', 'tn-linde-001', 'tp-linde-master', 'tp-linde-pgp', 'Remove Bulk content from PGP output', 'All Bulk-specific sections, pricing, and references must be stripped from the PGP output pack.', 'cross_references', 'would_block', 'critical', true, 'Content filter would run automatically', ''),
('sc-07', 'tn-linde-001', 'tp-linde-master', 'tp-linde-pgp', 'Remove internal notes and draft comments', 'All internal notes, working comments, and draft markers must be removed from the external output.', 'internal_notes', 'would_block', 'high', true, 'Internal note scanner would run automatically', ''),
('sc-08', 'tn-linde-001', 'tp-linde-master', 'tp-linde-pgp', 'Check PGP placeholders completed', 'All submission-critical placeholders for the PGP pack must have values.', 'placeholders', 'would_block', 'critical', true, 'Placeholder register feeds this check', ''),
('sc-09', 'tn-linde-001', 'tp-linde-master', 'tp-linde-pgp', 'Check PGP required documents ready', 'All required documents for the PGP submission must be uploaded and approved.', 'required_documents', 'would_block', 'high', true, 'Required documents register feeds this check', ''),
('sc-10', 'tn-linde-001', 'tp-linde-master', 'tp-linde-pgp', 'Check compliance gaps resolved', 'Non-compliant and clarification-required items must be resolved before production output.', 'compliance', 'warning', 'medium', false, 'Compliance matrix feeds this check', '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tender_pack_outputs (id, tender_workspace_id, tender_pack_id, source_pack_id, output_name, pack_name, output_type, format, version, status, generated_by, generated_at, watermark, is_test_output, would_be_submittable_in_production, mock_warnings_count, notes) VALUES
('po-001', 'tn-linde-001', 'tp-linde-bulk', 'tp-linde-master', 'Bulk Transportation Pack — TEST OUTPUT', 'Bulk Transportation Pack', 'Split Pack Output', 'PDF Mock', 'v0.1-test', 'generated_with_warnings', 'Amin Al-Halabi', '2026-04-29T10:30:00Z', 'TEST OUTPUT — NOT FOR CLIENT SUBMISSION', true, false, 5, '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tender_submission_emails (id, tender_workspace_id, tender_pack_id, pack_name, email_type, to_address, cc_external, cc_internal, subject, body, attachment_size_mb, status, simulated, submitted_by, submitted_at, warnings_count, notes) VALUES
('se-bulk', 'tn-linde-001', 'tp-linde-bulk', 'Bulk Transportation Pack', 'bulk_submission', 'tender@linde-sigas.com', 'procurement@linde-sigas.com', 'amin.alhalabi@hala.com', 'Linde SIGAS Transportation Tender — Bulk Pack Submission', 'Please find attached our Bulk Transportation proposal...', 12.5, 'draft_mock', false, '', NULL, 2, ''),
('se-pgp', 'tn-linde-001', 'tp-linde-pgp', 'PGP Transportation Pack', 'pgp_submission', 'tender@linde-sigas.com', 'procurement@linde-sigas.com', 'amin.alhalabi@hala.com', 'Linde SIGAS Transportation Tender — PGP Pack Submission', 'Please find attached our PGP proposal...', 8.2, 'draft_mock', false, '', NULL, 1, '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tender_submission_email_attachments (id, email_id, file_name, document_type, format, required, included, status, size_mb, notes) VALUES
('att-1', 'se-bulk', 'Linde_Bulk_Technical_Proposal.pdf', 'Technical Proposal', 'PDF', true, true, 'ready_mock', 4.5, ''),
('att-2', 'se-bulk', 'Linde_Bulk_Commercial_OBK.xlsx', 'Pricing', 'Excel', true, false, 'missing', 0, ''),
('att-3', 'se-bulk', 'Compliance_Pack_Bulk.pdf', 'Compliance', 'PDF', true, false, 'warning', 8, ''),
('att-4', 'se-pgp', 'Linde_PGP_Technical_Proposal.pdf', 'Technical Proposal', 'PDF', true, true, 'ready_mock', 3.2, ''),
('att-5', 'se-pgp', 'Linde_PGP_Commercial_OBK.xlsx', 'Pricing', 'Excel', true, false, 'missing', 0, ''),
('att-6', 'se-pgp', 'Compliance_Pack_PGP.pdf', 'Compliance', 'PDF', true, true, 'ready_mock', 5, '')
ON CONFLICT (id) DO NOTHING;

