/**
 * Server-side PDF Generator — Sprint 6
 * Uses PDFKit for reliable server-side generation.
 * Returns a Buffer. No client-side print-to-PDF.
 */
import PDFDocument from 'pdfkit';

interface PdfSection {
  type: 'heading' | 'subheading' | 'text' | 'label-value' | 'table' | 'spacer' | 'divider' | 'badge' | 'kpi-table';
  text?: string;
  label?: string;
  value?: string;
  rows?: Array<Record<string, string>>;
  columns?: string[];
}

interface PdfRenderInput {
  title: string;
  subtitle?: string;
  documentNumber: string;
  customerName?: string;
  generatedDate: string;
  sections: PdfSection[];
  footer?: string;
}

const NAVY = '#1B2A4A';
const GRAY = '#6B7280';
const LIGHT = '#F3F4F6';

export async function generatePdfBuffer(input: PdfRenderInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Title: input.title, Author: 'Hala Commercial Engine', Creator: 'Hala PDF Generator' } });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ─── Header ────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 80).fill(NAVY);
      doc.fontSize(18).fillColor('#FFFFFF').text(input.title, 50, 25, { width: doc.page.width - 100 });
      if (input.subtitle) doc.fontSize(9).fillColor('#CBD5E1').text(input.subtitle, 50, 50);
      doc.fontSize(8).fillColor('#CBD5E1').text(input.documentNumber, doc.page.width - 200, 25, { width: 150, align: 'right' });
      doc.text(input.generatedDate, doc.page.width - 200, 38, { width: 150, align: 'right' });
      if (input.customerName) doc.text(input.customerName, doc.page.width - 200, 51, { width: 150, align: 'right' });

      doc.y = 100;

      // ─── Sections ──────────────────────────────────
      for (const section of input.sections) {
        if (doc.y > doc.page.height - 80) doc.addPage();

        switch (section.type) {
          case 'heading':
            doc.moveDown(0.5).fontSize(13).fillColor(NAVY).text(section.text || '', { underline: false });
            doc.moveTo(50, doc.y + 2).lineTo(doc.page.width - 50, doc.y + 2).strokeColor(NAVY).lineWidth(0.5).stroke();
            doc.moveDown(0.4);
            break;
          case 'subheading':
            doc.moveDown(0.3).fontSize(10).fillColor(NAVY).text(section.text || '');
            doc.moveDown(0.2);
            break;
          case 'text':
            doc.fontSize(9).fillColor('#374151').text(section.text || '', { lineGap: 3 });
            doc.moveDown(0.3);
            break;
          case 'label-value':
            doc.fontSize(8).fillColor(GRAY).text(section.label || '', { continued: true }).fillColor('#111827').text(`  ${section.value || '—'}`);
            doc.moveDown(0.15);
            break;
          case 'badge':
            doc.fontSize(8).fillColor(NAVY).text(`● ${section.text || ''}`, { lineGap: 2 });
            doc.moveDown(0.2);
            break;
          case 'spacer':
            doc.moveDown(0.6);
            break;
          case 'divider':
            doc.moveDown(0.3).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#E5E7EB').lineWidth(0.3).stroke();
            doc.moveDown(0.3);
            break;
          case 'table':
          case 'kpi-table':
            if (section.columns && section.rows) {
              const cols = section.columns;
              const colW = (doc.page.width - 100) / cols.length;
              // Header row
              doc.rect(50, doc.y, doc.page.width - 100, 18).fill(LIGHT);
              let hx = 50;
              for (const col of cols) { doc.fontSize(7).fillColor(NAVY).text(col, hx + 4, doc.y + 4, { width: colW - 8 }); hx += colW; }
              doc.y += 20;
              // Data rows
              for (const row of section.rows) {
                if (doc.y > doc.page.height - 60) doc.addPage();
                let rx = 50;
                const vals = cols.map(c => row[c] || row[c.toLowerCase()] || '');
                for (const val of vals) { doc.fontSize(7.5).fillColor('#374151').text(val, rx + 4, doc.y, { width: colW - 8 }); rx += colW; }
                doc.y += 15;
                doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#F3F4F6').lineWidth(0.2).stroke();
                doc.y += 2;
              }
              doc.moveDown(0.3);
            }
            break;
        }
      }

      // ─── Footer ────────────────────────────────────
      const footer = input.footer || 'Generated by Hala Commercial Engine — Confidential';
      doc.fontSize(7).fillColor(GRAY).text(footer, 50, doc.page.height - 40, { width: doc.page.width - 100, align: 'center' });

      doc.end();
    } catch (err) { reject(err); }
  });
}
